import type {
  BleedingCase,
  InvestigationOption,
  InvestigationScoreItem,
} from "./bleedingTypes";

const standardScreeningNotes = {
  cbc: "ช่วยประเมินระดับฮีโมโกลบิน เม็ดเลือดขาว และจำนวนเกล็ดเลือด",
  smear: "ช่วยยืนยันจำนวนและลักษณะเกล็ดเลือด รวมทั้งค้นหาเซลล์ผิดปกติ",
  pt: "ประเมิน extrinsic และ common coagulation pathway",
  aptt: "ประเมิน intrinsic และ common coagulation pathway",
} as const;

const score = (
  id: string,
  label: string,
  points: number,
  requiredAll?: InvestigationScoreItem["requiredAll"],
  requiredAny?: InvestigationScoreItem["requiredAny"],
  avoided?: InvestigationScoreItem["avoided"],
): InvestigationScoreItem => ({ id, label, points, requiredAll, requiredAny, avoided });

export const bleedingInvestigationOptions: InvestigationOption[] = [
  { id: "cbc", label: "CBC พร้อมจำนวนเกล็ดเลือดและ differential count", group: "เบื้องต้น" },
  { id: "smear", label: "Peripheral blood smear", group: "เบื้องต้น" },
  { id: "pt", label: "PT", group: "เบื้องต้น" },
  { id: "aptt", label: "aPTT", group: "เบื้องต้น" },
  { id: "fibrinogen", label: "Fibrinogen", group: "เบื้องต้น" },
  { id: "dDimer", label: "D-dimer", group: "เบื้องต้น" },
  { id: "reticulocyte", label: "Reticulocyte count", group: "เบื้องต้น" },
  { id: "crossmatch", label: "หมู่เลือดและ crossmatch", group: "เบื้องต้น" },
  { id: "factor8", label: "Factor VIII activity", group: "จำเพาะ" },
  { id: "factor9", label: "Factor IX activity", group: "จำเพาะ" },
  { id: "vwfAntigen", label: "vWF antigen", group: "จำเพาะ" },
  { id: "vwfActivity", label: "vWF activity / ristocetin cofactor activity", group: "จำเพาะ" },
  { id: "plateletFunction", label: "Platelet function test", group: "จำเพาะ" },
  { id: "eosinophil", label: "Absolute eosinophil count", group: "จำเพาะ" },
  { id: "mixingStudy", label: "Mixing study / inhibitor assay", group: "จำเพาะ" },
  { id: "stool", label: "ตรวจอุจจาระหาไข่พยาธิและพยาธิ", group: "เพิ่มเติม" },
  { id: "lft", label: "Liver function test", group: "เพิ่มเติม" },
  { id: "rft", label: "Renal function test", group: "เพิ่มเติม" },
  { id: "boneMarrow", label: "Bone marrow aspiration", group: "เพิ่มเติม" },
  { id: "flowCytometry", label: "Flow cytometry", group: "เพิ่มเติม" },
];

export const bleedingCases: BleedingCase[] = [
  {
    id: "itp",
    diagnosis: "Immune thrombocytopenia (ITP)",
    diagnosisCategory: "ภาวะเกล็ดเลือดต่ำที่เกิดจากภูมิคุ้มกัน",
    identity: {
      childName: "เด็กหญิงพิชญาภา",
      childSurname: "สุขสวัสดิ์",
      childNickname: "น้องพิม",
      childAge: "4 ปี",
      childSex: "หญิง",
      parentName: "นางสาวมณีรัตน์",
      parentSurname: "สุขสวัสดิ์",
      informantRelationship: "มารดา",
    },
    openingStatement: "ลูกมีจุดเลือดออกกับจ้ำเลือดตามตัวค่ะ",
    broadAnswer: "เห็นเป็นจุดแดงเล็ก ๆ กับจ้ำตามแขนขามาประมาณ 3 วันค่ะ",
    responseRules: [
      {
        id: "siblings",
        domainIds: ["family"],
        keywords: ["มีพี่น้อง", "พี่น้องไหม", "พี่หรือน้อง", "มีพี่", "มีน้อง", "พี่ชาย", "น้องชาย", "พี่สาว", "น้องสาว", "ลูกกี่คน", "ลูกคนที่"],
        answer: "มีพี่ชาย 1 คน อายุ 7 ปีค่ะ สุขภาพแข็งแรงดี ไม่มีจ้ำเลือดหรือเลือดออกง่ายเหมือนน้อง",
      },
      {
        id: "vaccination",
        domainIds: ["infection"],
        keywords: ["วัคซีน", "ฉีดวัคซีน", "สมุดวัคซีน", "mmr", "เชื้อเป็น", "live vaccine"],
        answer: "วัคซีนพื้นฐานครบตามวัยค่ะ ล่าสุดเพิ่งฉีด MMR เข็มเก็บตกเมื่อประมาณ 3 สัปดาห์ก่อน เพราะในสมุดวัคซีนขาดเข็มที่สองค่ะ",
      },
      { id: "duration", domainIds: ["onset"], keywords: ["เริ่ม", "นาน", "กี่วัน", "กี่สัปดาห์", "กี่เดือน", "เมื่อไหร่"], answer: "เป็นมาประมาณ 3 วันค่ะ" },
      { id: "epistaxis", domainIds: ["site", "mucocutaneous"], keywords: ["กำเดา", "จมูก"], answer: "มีเลือดกำเดาออกเล็กน้อยครั้งหนึ่งค่ะ แล้วหยุดเอง" },
      { id: "gum", domainIds: ["mucocutaneous"], keywords: ["ไรฟัน", "เหงือก"], answer: "ไม่มีเลือดออกตามไรฟันรุนแรงค่ะ" },
      { id: "gi-gu", domainIds: ["site"], keywords: ["ถ่ายดำ", "ถ่ายเลือด", "อุจจาระ", "ปัสสาวะ", "ฉี่"], answer: "ไม่มีถ่ายดำ ไม่มีถ่ายเลือด และไม่มีปัสสาวะเป็นเลือดค่ะ" },
      { id: "deep", domainIds: ["deep"], keywords: ["ข้อบวม", "ปวดข้อ", "เข่าบวม", "ข้อเท้า", "กล้ามเนื้อ", "เลือดออกในข้อ", "ช้ำลึก"], answer: "ไม่มีข้อบวมหรือปวดข้อมากค่ะ ไม่มีกล้ามเนื้อบวมค่ะ" },
      { id: "infection", domainIds: ["infection"], keywords: ["หวัด", "ติดเชื้อ", "ป่วยก่อน", "ไอ", "น้ำมูก", "เจ็บคอ", "ท้องเสีย"], answer: "ก่อนหน้านี้ประมาณ 1–2 สัปดาห์มีไข้กับน้ำมูกเหมือนเป็นหวัดค่ะ" },
      { id: "fever", domainIds: ["infection", "redflags"], keywords: ["ไข้"], answer: "ตอนนี้ไม่มีไข้ค่ะ แต่ก่อนหน้านี้ 1–2 สัปดาห์เคยมีไข้กับน้ำมูกเหมือนหวัดค่ะ" },
      { id: "trauma", domainIds: ["trauma"], keywords: ["กระแทก", "อุบัติเหตุ", "ล้ม", "ถอนฟัน", "ผ่าตัด", "ขลิบ", "ฉีดยา"], answer: "จ้ำหลายจุดขึ้นเองค่ะ ไม่ได้กระแทกแรง และไม่เคยมีเลือดออกผิดปกติหลังหัตถการค่ะ" },
      { id: "medication", domainIds: ["medication"], keywords: ["ยา", "aspirin", "แอสไพริน", "nsaid", "ibuprofen", "สมุนไพร", "อาหารเสริม"], answer: "ตอนเป็นไข้กิน paracetamol ค่ะ ไม่ได้กิน aspirin หรือยาแก้อักเสบค่ะ" },
      { id: "redflags", domainIds: ["redflags"], keywords: ["ซีด", "น้ำหนัก", "เบื่ออาหาร", "ปวดกระดูก", "ต่อมน้ำเหลือง", "ตับ", "ม้าม", "ท้องโต", "เหงื่อกลางคืน"], answer: "ยังเล่นได้ กินได้ ไม่มีน้ำหนักลด ไม่มีปวดกระดูก ไม่เห็นต่อมน้ำเหลืองโตหรือท้องโตค่ะ" },
      { id: "family", domainIds: ["family"], keywords: ["ครอบครัว", "ญาติ", "น้า", "ลุง", "พี่น้อง", "hemophilia", "ฮีโมฟีเลีย", "von willebrand", "กรรมพันธุ์"], answer: "ไม่มีใครในครอบครัวเลือดออกง่ายหรือเป็น hemophilia ค่ะ" },
      { id: "past", domainIds: [], keywords: ["เคยเป็น", "เคยเลือดออก", "เคยได้รับเลือด", "เคยนอน", "โรคประจำตัว", "เคยตรวจเลือด", "เกล็ดเลือดต่ำ", "เคยช้ำ"], answer: "ไม่มีโรคประจำตัว ไม่เคยเลือดออกง่าย ไม่เคยได้รับเลือด และไม่เคยตรวจพบเกล็ดเลือดต่ำค่ะ" },
      { id: "pattern", domainIds: ["site", "mucocutaneous"], keywords: ["จุดเลือด", "จ้ำเลือด", "petechiae", "ecchymosis", "เลือดออกที่ไหน", "ลักษณะ"], answer: "เป็นจุดเลือดออกเล็ก ๆ กับจ้ำเลือดตามแขนขาค่ะ" },
      { id: "activity", domainIds: [], keywords: ["เดิน", "วิ่ง", "เล่น", "กิจกรรม", "ซน"], answer: "ยังกินได้และเล่นได้ตามปกติค่ะ" },
    ],
    physicalExam: {
      positives: ["พบจุดเลือดออกเล็ก ๆ ที่ขาทั้งสองข้าง", "พบจ้ำเลือดหลายตำแหน่ง"],
      negatives: ["ไม่ซีดชัดเจน", "ไม่มีตาเหลือง", "ไม่พบต่อมน้ำเหลืองโต", "ตับและม้ามไม่โต", "ไม่มีข้อบวม", "ไม่มีเลือดออกรุนแรงขณะตรวจ"],
    },
    expectedLabPattern: [
      "CBC: Hb และ WBC ปกติ แต่จำนวนเกล็ดเลือดต่ำมาก",
      "Peripheral blood smear: isolated thrombocytopenia และไม่พบ blast",
      "PT และ aPTT ปกติ",
    ],
    investigationScores: [
      score("cbc", "เลือก CBC เพื่อประเมินจำนวนเกล็ดเลือด", 6, ["cbc"]),
      score("smear", "เลือก peripheral blood smear เพื่อยืนยัน isolated thrombocytopenia และค้นหา blast", 5, ["smear"]),
      score("coag", "เลือก coagulation screening ที่เหมาะสม", 4, ["pt", "aptt"]),
      score("avoid-marrow", "หลีกเลี่ยง bone marrow aspiration ในเคส typical ITP", 3, undefined, undefined, ["boneMarrow"]),
      score("pattern", "วางชุดตรวจที่ช่วยจำแนก isolated thrombocytopenia", 2, ["cbc", "smear"]),
    ],
    investigationNotes: {
      ...standardScreeningNotes,
      boneMarrow: "ยังไม่ใช่การตรวจเบื้องต้นในเด็กที่มีลักษณะ typical ITP และไม่มี red flags",
      flowCytometry: "ยังไม่จำเป็นหาก CBC และ smear ไม่พบข้อมูลชวนสงสัย leukemia",
    },
    problemScoring: {
      patternKeywords: ["mucocutaneous", "เยื่อบุ", "ผิวหนัง", "platelet", "เกล็ดเลือด", "petechiae", "จุดเลือด"],
      positiveKeywords: ["3 วัน", "สามวัน", "จุดเลือด", "จ้ำเลือด", "กำเดา", "หวัด", "ติดเชื้อ", "วัคซีน", "mmr", "3 สัปดาห์"],
      negativeKeywords: ["ไม่มีข้อ", "ไม่มีกล้ามเนื้อ", "ไม่มีไข้", "ไม่มีน้ำหนัก", "ไม่มีปวดกระดูก", "ตับม้ามไม่โต", "ไม่มีต่อมน้ำเหลือง"],
      differentialKeywords: ["itp", "immune thrombocytopenia", "leukemia", "aplastic", "platelet disorder", "เกล็ดเลือดต่ำ"],
      impressionKeywords: ["itp", "immune thrombocytopenia", "เกล็ดเลือดต่ำจากภูมิคุ้มกัน"],
    },
    modelProblemList: [
      "เด็กหญิงอายุ 4 ปี มี acute mucocutaneous bleeding ได้แก่ petechiae และ ecchymoses 3 วัน",
      "มีเลือดกำเดาเล็กน้อย แต่ไม่มี major bleeding",
      "มีประวัติติดเชื้อทางเดินหายใจก่อนหน้า 1–2 สัปดาห์",
      "ได้รับวัคซีน MMR เข็มเก็บตกเมื่อประมาณ 3 สัปดาห์ก่อน ซึ่งเป็น live attenuated vaccine และอาจเป็น trigger ของ ITP ได้แม้พบไม่บ่อย",
      "ไม่มีข้อบวม กล้ามเนื้อบวม หรือเลือดออกลึก ทำให้ coagulation factor deficiency เด่นชัดน้อยลง",
      "ไม่มีไข้ปัจจุบัน น้ำหนักลด ปวดกระดูก ต่อมน้ำเหลืองโต หรือตับม้ามโต จึงไม่มี red flags ของ leukemia ชัดเจน",
      "ภาพรวมเข้าได้กับ thrombocytopenic bleeding โดยคิดถึง acute ITP",
    ],
    differentialDiagnosis: ["Acute ITP", "Acute leukemia", "Aplastic anemia", "Platelet function disorder"],
    finalImpression: "สงสัย acute immune thrombocytopenia (ITP) หลังการติดเชื้อไวรัส",
    suggestedInvestigations: ["CBC พร้อมจำนวนเกล็ดเลือด", "Peripheral blood smear", "PT และ aPTT เมื่อ bleeding pattern ไม่ชัดหรือก่อนหัตถการ", "พิจารณาตรวจไวรัสเฉพาะเมื่อมีข้อบ่งชี้", "Bone marrow examination เฉพาะเมื่อมี atypical features หรือสงสัย malignancy"],
    teachingSummary: "ITP มักมาด้วย mucocutaneous bleeding เช่น petechiae, ecchymoses และ epistaxis เด็กมักดูสบายดี ไม่มีตับม้ามโตหรือต่อมน้ำเหลืองโต และ CBC มักพบ isolated thrombocytopenia ควรถามทั้งการติดเชื้อและวัคซีนก่อนหน้า โดย MMR ซึ่งเป็น live attenuated vaccine อาจสัมพันธ์กับ ITP ได้แต่พบไม่บ่อย",
  },
  {
    id: "hemophilia-a",
    diagnosis: "Hemophilia A",
    diagnosisCategory: "ภาวะขาด coagulation factor VIII แต่กำเนิด",
    identity: {
      childName: "เด็กชายธนภัทร",
      childSurname: "เกียรติกุล",
      childNickname: "น้องเต้",
      childAge: "3 ปี",
      childSex: "ชาย",
      parentName: "นางสาวสุชาดา",
      parentSurname: "เกียรติกุล",
      informantRelationship: "มารดา",
    },
    openingStatement: "ลูกเข่าบวมและปวดมากหลังล้มค่ะ",
    broadAnswer: "เข่าขวาบวมและปวดหลังล้มตอนเล่นตั้งแต่เมื่อวานค่ะ",
    responseRules: [
      {
        id: "siblings",
        domainIds: ["family"],
        keywords: ["มีพี่น้อง", "พี่น้องไหม", "พี่หรือน้อง", "มีพี่", "มีน้อง", "พี่ชาย", "น้องชาย", "พี่สาว", "น้องสาว", "ลูกกี่คน", "ลูกคนที่"],
        answer: "มีพี่ชาย 1 คน อายุ 6 ปีค่ะ พี่ชายเคยข้อบวมหลังล้มเบา ๆ และเลือดหยุดช้าหลังแผลเล็ก ๆ คล้ายกันค่ะ ส่วนน้าชายของน้องทางฝ่ายแม่ก็มีข้อบวมและเลือดออกง่ายบ่อยค่ะ",
      },
      {
        id: "vaccination",
        domainIds: ["trauma"],
        keywords: ["วัคซีน", "ฉีดวัคซีน", "สมุดวัคซีน", "laje", "เจอี", "เชื้อเป็น", "live vaccine"],
        answer: "วัคซีนพื้นฐานครบตามวัยค่ะ ล่าสุดฉีดวัคซีนไข้สมองอักเสบเจอีชนิดเชื้อเป็นอ่อนฤทธิ์เข็มที่ 2 ตอนอายุ 2 ปีครึ่ง ประมาณ 6 เดือนก่อนค่ะ ตอนฉีดมีรอยช้ำและบวมกว่าปกติบริเวณที่ฉีดค่ะ",
      },
      { id: "duration", domainIds: ["onset"], keywords: ["เริ่ม", "นาน", "กี่วัน", "กี่สัปดาห์", "เมื่อไหร่"], answer: "เข่าบวมและปวดมาตั้งแต่เมื่อวานค่ะ" },
      { id: "trauma", domainIds: ["trauma"], keywords: ["ล้ม", "กระแทก", "อุบัติเหตุ", "เล่น", "กิจกรรม"], answer: "ก่อนหน้าเขาล้มตอนเล่นค่ะ ไม่ได้กระแทกแรงมาก แต่เข่าบวมมากเลยค่ะ" },
      { id: "deep", domainIds: ["site", "deep"], keywords: ["ข้อบวม", "ปวดข้อ", "เข่าบวม", "ข้อเท้า", "เลือดออกในข้อ", "กล้ามเนื้อ", "ช้ำลึก", "ลงน้ำหนัก"], answer: "เข่าขวาบวม ปวด และลงน้ำหนักไม่ค่อยได้ค่ะ" },
      { id: "mucosa", domainIds: ["mucocutaneous"], keywords: ["จุดเลือด", "petechiae", "กำเดา", "ไรฟัน", "เหงือก", "ประจำเดือน"], answer: "ไม่มีจุดเลือดออกเล็ก ๆ ไม่มีเลือดกำเดาบ่อย และไม่มีเลือดออกตามไรฟันค่ะ" },
      { id: "gi-gu", domainIds: ["site"], keywords: ["ถ่ายดำ", "ถ่ายเลือด", "อุจจาระ", "ปัสสาวะ", "ฉี่"], answer: "ไม่มีถ่ายดำ ถ่ายเลือด หรือปัสสาวะเป็นเลือดค่ะ" },
      { id: "procedure", domainIds: ["trauma"], keywords: ["ฉีดยา", "วัคซีน", "ถอนฟัน", "ผ่าตัด", "ขลิบ", "แผล", "เลือดหยุด"], answer: "เคยมีรอยช้ำใหญ่หลังฉีดวัคซีน และเหมือนเลือดหยุดช้ากว่าปกติค่ะ น้องไม่ได้ขลิบค่ะ" },
      { id: "infection", domainIds: ["infection"], keywords: ["ไข้", "หวัด", "ไอ", "เจ็บคอ", "ท้องเสีย", "ติดเชื้อ", "ป่วยก่อน"], answer: "ไม่มีไข้และไม่มีอาการติดเชื้อมาก่อนค่ะ" },
      { id: "medication", domainIds: ["medication"], keywords: ["ยา", "aspirin", "แอสไพริน", "nsaid", "ibuprofen", "สมุนไพร", "อาหารเสริม"], answer: "ไม่ได้กิน aspirin หรือยาแก้อักเสบค่ะ" },
      { id: "redflags", domainIds: ["redflags"], keywords: ["ซีด", "น้ำหนัก", "เบื่ออาหาร", "ปวดกระดูก", "ต่อมน้ำเหลือง", "ตับ", "ม้าม", "ท้องโต", "เหงื่อกลางคืน"], answer: "ไม่มีไข้ ไม่มีน้ำหนักลด ไม่มีปวดกระดูกเรื้อรัง และไม่เห็นต่อมน้ำเหลืองโตค่ะ" },
      { id: "family", domainIds: ["family"], keywords: ["ครอบครัว", "ญาติ", "น้า", "ลุง", "ผู้ชาย", "พี่น้อง", "hemophilia", "ฮีโมฟีเลีย", "กรรมพันธุ์"], answer: "น้าชายฝ่ายแม่เคยมีปัญหาเลือดออกง่ายและข้อบวมบ่อยค่ะ" },
      { id: "past", domainIds: [], keywords: ["เคยเป็น", "เคยเลือดออก", "เคยได้รับเลือด", "เคยนอน", "โรคประจำตัว", "เคยตรวจเลือด", "เคยช้ำ"], answer: "เคยมีรอยช้ำใหญ่หลังฉีดวัคซีนและเลือดหยุดช้าหลังแผลเล็ก ๆ แต่ไม่เคยได้รับเลือดค่ะ" },
      { id: "bruising", domainIds: ["site"], keywords: ["จ้ำเลือด", "ฟกช้ำ", "ecchymosis"], answer: "เคยมีรอยช้ำใหญ่หลังฉีดวัคซีนค่ะ แต่ไม่มีจ้ำตื้น ๆ จำนวนมากตามตัว" },
    ],
    physicalExam: {
      positives: ["เข่าขวาบวม", "ขยับเข่าขวาได้น้อยลง", "ปวดเมื่อขยับข้อ", "พบจ้ำเลือดลึกบริเวณต้นขา"],
      negatives: ["ไม่พบจุดเลือดออกเล็ก ๆ", "ไม่พบต่อมน้ำเหลืองโตทั่วไป", "ตับและม้ามไม่โต", "ไม่มีไข้"],
    },
    expectedLabPattern: [
      "CBC: Hb ปกติหรืออาจต่ำเล็กน้อย, WBC และจำนวนเกล็ดเลือดปกติ",
      "PT ปกติ แต่ aPTT ยาว",
      "Factor VIII activity ต่ำ",
    ],
    investigationScores: [
      score("cbc", "เลือก CBC เพื่อดูระดับ Hb และยืนยันว่าเกล็ดเลือดปกติ", 3, ["cbc"]),
      score("pt", "เลือก PT เพื่อจำแนก coagulation pathway", 3, ["pt"]),
      score("aptt", "เลือก aPTT ซึ่งไวต่อ intrinsic pathway", 4, ["aptt"]),
      score("factor8", "เลือก Factor VIII activity เพื่อยืนยัน Hemophilia A", 5, ["factor8"]),
      score("factor9", "เลือก Factor IX activity เพื่อแยก Hemophilia B", 3, ["factor9"]),
      score("mixing", "เลือก mixing study หรือ inhibitor assay ในการประเมินต่อยอด", 2, ["mixingStudy"]),
    ],
    investigationNotes: {
      ...standardScreeningNotes,
      factor8: "เป็นการตรวจยืนยันที่สำคัญสำหรับ Hemophilia A",
      factor9: "ช่วยแยก Hemophilia A ออกจาก Hemophilia B",
      mixingStudy: "ช่วยแยก factor deficiency จาก inhibitor โดยเฉพาะเมื่อ aPTT ยาว",
      plateletFunction: "ไม่ใช่การตรวจหลักเมื่อ pattern เป็น deep bleeding และสงสัย factor deficiency",
    },
    problemScoring: {
      patternKeywords: ["deep", "เลือดออกลึก", "hemarthrosis", "เลือดออกในข้อ", "ข้อ", "coagulation factor"],
      positiveKeywords: ["เข่าขวา", "ข้อบวม", "ปวด", "ล้ม", "ฉีดวัคซีน", "พี่ชาย", "น้าชาย", "ฝ่ายแม่"],
      negativeKeywords: ["ไม่มีจุดเลือด", "ไม่มี petechiae", "ไม่มีเลือดกำเดา", "ไม่มีไข้", "ตับม้ามไม่โต", "ไม่มีต่อมน้ำเหลือง"],
      differentialKeywords: ["hemophilia", "ฮีโมฟีเลีย", "factor viii", "factor ix", "von willebrand", "septic arthritis", "trauma"],
      impressionKeywords: ["hemophilia a", "ฮีโมฟีเลีย เอ", "factor viii", "แฟกเตอร์ 8"],
    },
    modelProblemList: [
      "เด็กชายอายุ 3 ปี มี deep bleeding pattern ได้แก่ hemarthrosis ที่เข่าขวาหลัง trauma เล็กน้อย",
      "มีประวัติเลือดออกหรือช้ำมากกว่าปกติหลังฉีดวัคซีน",
      "ไม่มี petechiae หรือ mucosal bleeding เด่น ทำให้ platelet-type bleeding เด่นชัดน้อยลง",
      "พี่ชายและน้าชายฝ่ายแม่มีข้อบวมและเลือดออกง่าย สนับสนุน X-linked inherited bleeding disorder",
      "ตรวจร่างกายพบข้อเข่าบวม ปวด และขยับได้น้อย",
      "ภาพรวมเข้าได้กับ hemophilia โดยเฉพาะ Hemophilia A",
    ],
    differentialDiagnosis: ["Hemophilia A", "Hemophilia B", "Severe von Willebrand disease", "Septic arthritis หรือ traumatic joint injury"],
    finalImpression: "สงสัย Hemophilia A จาก congenital factor VIII deficiency",
    suggestedInvestigations: ["CBC พร้อมจำนวนเกล็ดเลือด", "PT", "aPTT", "Factor VIII activity", "Factor IX activity เพื่อแยก Hemophilia A และ B", "Mixing study เมื่อสงสัย acquired inhibitor", "Inhibitor assay ในผู้ที่เคยได้รับ factor หรือไม่ตอบสนองต่อการรักษา"],
    teachingSummary: "Hemophilia มักมี deep tissue bleeding หรือ hemarthrosis โดยเฉพาะในเด็กชาย อาจมีประวัติครอบครัวฝ่ายแม่ จำนวนเกล็ดเลือดและ PT มักปกติ แต่ aPTT ยาว และต้องยืนยันด้วย factor assay",
  },
  {
    id: "von-willebrand",
    diagnosis: "von Willebrand disease type 1",
    diagnosisCategory: "ความผิดปกติของ von Willebrand factor ที่มักถ่ายทอดแบบ autosomal dominant",
    identity: {
      childName: "เด็กหญิงณิชาภัทร",
      childSurname: "วัฒนานนท์",
      childNickname: "น้องมะปราง",
      childAge: "13 ปี",
      childSex: "หญิง",
      parentName: "นางสาวภัทรา",
      parentSurname: "วัฒนานนท์",
      informantRelationship: "มารดา",
    },
    openingStatement: "ลูกมีเลือดกำเดาออกบ่อย และประจำเดือนมามากค่ะ",
    broadAnswer: "ช่วงนี้เลือดกำเดาออกบ่อยและประจำเดือนก็มามากค่ะ",
    responseRules: [
      {
        id: "siblings",
        domainIds: ["family"],
        keywords: ["มีพี่น้อง", "พี่น้องไหม", "พี่หรือน้อง", "มีพี่", "มีน้อง", "พี่ชาย", "น้องชาย", "พี่สาว", "น้องสาว", "ลูกกี่คน", "ลูกคนที่"],
        answer: "มีพี่สาว 1 คน อายุ 16 ปีค่ะ พี่สาวก็มีเลือดกำเดาออกบ่อย ช้ำง่าย และประจำเดือนมามากคล้ายกันค่ะ ส่วนแม่ก็ประจำเดือนมามากและเคยเลือดออกนานหลังทำฟัน",
      },
      {
        id: "vaccination",
        domainIds: [],
        keywords: ["วัคซีน", "ฉีดวัคซีน", "สมุดวัคซีน", "dt", "บาดทะยัก", "hpv", "เชื้อเป็น", "live vaccine"],
        answer: "วัคซีนตามวัยครบค่ะ ล่าสุดฉีดวัคซีนคอตีบ-บาดทะยัก หรือ dT ที่โรงเรียนตอน ป.6 ประมาณ 1 ปีก่อนค่ะ หลังฉีดไม่มีเลือดออกหรือก้อนบวมผิดปกติ",
      },
      { id: "epistaxis", domainIds: ["site", "mucocutaneous"], keywords: ["กำเดา", "จมูก"], answer: "เลือดกำเดาออกเดือนละหลายครั้ง และบางครั้งนานกว่าจะหยุดค่ะ" },
      { id: "gum", domainIds: ["mucocutaneous"], keywords: ["ไรฟัน", "เหงือก", "แปรงฟัน"], answer: "มีเลือดออกตามไรฟันบ้างเวลาแปรงฟันค่ะ" },
      { id: "menstruation", domainIds: ["site", "mucocutaneous"], keywords: ["ประจำเดือน", "ผ้าอนามัย", "กี่วัน", "รอบเดือน"], answer: "ประจำเดือนมามากค่ะ ใช้ผ้าอนามัยหลายแผ่นต่อวัน และมานานประมาณ 7–8 วันค่ะ" },
      { id: "duration", domainIds: ["onset"], keywords: ["เริ่ม", "นาน", "กี่สัปดาห์", "กี่เดือน", "เมื่อไหร่", "ตั้งแต่"], answer: "เลือดกำเดาออกง่ายตั้งแต่เด็กค่ะ แต่ช่วงหลังเป็นบ่อยขึ้น" },
      { id: "bruising", domainIds: ["site", "mucocutaneous"], keywords: ["จ้ำเลือด", "ฟกช้ำ", "ecchymosis", "ช้ำง่าย"], answer: "มีจ้ำเลือดง่ายค่ะ บางครั้งไม่ได้กระแทกแรง" },
      { id: "deep", domainIds: ["deep"], keywords: ["ข้อบวม", "ปวดข้อ", "เข่าบวม", "เลือดออกในข้อ", "กล้ามเนื้อ", "ช้ำลึก"], answer: "ไม่มีข้อบวมหรือกล้ามเนื้อบวมค่ะ" },
      { id: "procedure", domainIds: ["trauma"], keywords: ["ถอนฟัน", "ผ่าตัด", "ขลิบ", "ฉีดยา", "แผล", "เลือดหยุด"], answer: "เคยถอนฟันแล้วเลือดซึมนานค่ะ" },
      { id: "gi-gu", domainIds: ["site"], keywords: ["ถ่ายดำ", "ถ่ายเลือด", "อุจจาระ", "ปัสสาวะ", "ฉี่"], answer: "ไม่มีถ่ายดำ ถ่ายเลือด หรือปัสสาวะเป็นเลือดค่ะ" },
      { id: "infection", domainIds: ["infection"], keywords: ["ไข้", "หวัด", "ไอ", "เจ็บคอ", "ท้องเสีย", "ติดเชื้อ", "ป่วยก่อน"], answer: "ไม่มีไข้และไม่มีอาการติดเชื้อนำมาก่อนค่ะ" },
      { id: "medication", domainIds: ["medication"], keywords: ["ยา", "aspirin", "แอสไพริน", "nsaid", "ibuprofen", "สมุนไพร", "อาหารเสริม"], answer: "ไม่ได้กิน aspirin หรือยาแก้อักเสบเป็นประจำค่ะ" },
      { id: "redflags", domainIds: ["redflags"], keywords: ["ซีด", "น้ำหนัก", "เบื่ออาหาร", "ปวดกระดูก", "ต่อมน้ำเหลือง", "ตับ", "ม้าม", "ท้องโต", "เหงื่อกลางคืน"], answer: "ไม่มีไข้ ไม่มีน้ำหนักลด ไม่มีปวดกระดูก ไม่เห็นต่อมน้ำเหลืองโตหรือท้องโตค่ะ" },
      { id: "family", domainIds: ["family"], keywords: ["ครอบครัว", "ญาติ", "แม่", "พ่อ", "พี่น้อง", "hemophilia", "von willebrand", "กรรมพันธุ์", "ประจำเดือนมากในครอบครัว"], answer: "แม่เองก็ประจำเดือนมามาก และเคยเลือดออกนานหลังทำฟันค่ะ" },
      { id: "past", domainIds: [], keywords: ["เคยเป็น", "เคยเลือดออก", "เคยได้รับเลือด", "เคยนอน", "โรคประจำตัว", "เคยตรวจเลือด"], answer: "เคยถอนฟันแล้วเลือดซึมนานค่ะ ไม่เคยได้รับเลือดและไม่มีโรคประจำตัว" },
    ],
    physicalExam: {
      positives: ["เยื่อบุตาซีดเล็กน้อย", "พบจ้ำเลือดเล็กน้อยที่แขนขา"],
      negatives: ["ขณะตรวจไม่มีเลือดกำเดาออก", "ไม่พบจุดเลือดออกเล็ก ๆ ชัดเจน", "ไม่มีข้อบวม", "ตับและม้ามไม่โต", "ไม่พบต่อมน้ำเหลืองโต"],
    },
    expectedLabPattern: [
      "CBC: Hb ปกติหรืออาจต่ำเล็กน้อยจากประจำเดือนมาก และจำนวนเกล็ดเลือดปกติ",
      "PT ปกติ ส่วน aPTT ปกติหรือยาวเล็กน้อย",
      "vWF antigen และ vWF activity ต่ำ",
      "Factor VIII อาจต่ำหรืออยู่ค่าต่ำของช่วงปกติ",
    ],
    investigationScores: [
      score("cbc", "เลือก CBC เพื่อประเมินซีดและจำนวนเกล็ดเลือด", 3, ["cbc"]),
      score("coag", "เลือก PT และ aPTT เป็น coagulation screening", 4, ["pt", "aptt"]),
      score("antigen", "เลือก vWF antigen", 5, ["vwfAntigen"]),
      score("activity", "เลือก vWF activity", 5, ["vwfActivity"]),
      score("factor8", "เลือก Factor VIII activity", 3, ["factor8"]),
    ],
    investigationNotes: {
      ...standardScreeningNotes,
      vwfAntigen: "ประเมินปริมาณ von Willebrand factor",
      vwfActivity: "ประเมินการทำงานของ von Willebrand factor",
      factor8: "ช่วยประเมินผลของ vWF ต่อการคงอยู่ของ Factor VIII",
      reticulocyte: "อาจพิจารณาเมื่อประเมินภาวะซีด แต่ไม่ใช่การยืนยัน vWD",
    },
    problemScoring: {
      patternKeywords: ["mucocutaneous", "เยื่อบุ", "ผิวหนัง", "กำเดา", "ประจำเดือน", "platelet-type"],
      positiveKeywords: ["กำเดา", "ไรฟัน", "ประจำเดือน", "7–8 วัน", "ถอนฟัน", "จ้ำเลือด", "พี่สาว", "แม่"],
      negativeKeywords: ["ไม่มีข้อ", "ไม่มีกล้ามเนื้อ", "ไม่มีไข้", "ไม่มีน้ำหนัก", "ตับม้ามไม่โต", "ไม่มีต่อมน้ำเหลือง"],
      differentialKeywords: ["von willebrand", "vwd", "platelet dysfunction", "itp", "hemophilia", "พาหะ"],
      impressionKeywords: ["von willebrand", "vwd", "วอนวิลลิแบรนด์"],
    },
    modelProblemList: [
      "เด็กหญิงอายุ 13 ปี มี mucocutaneous bleeding เรื้อรัง ได้แก่ epistaxis, gum bleeding, easy bruising และ menorrhagia",
      "มีประวัติเลือดออกนานหลังถอนฟัน",
      "มีประวัติครอบครัวในหลายรุ่น โดยพี่สาวมี epistaxis, easy bruising และ menorrhagia ส่วนแม่มีประจำเดือนมามากและเลือดออกนานหลังทำฟัน สนับสนุน autosomal dominant inheritance",
      "ไม่มี joint bleeding หรือ deep muscle bleeding ทำให้ severe hemophilia เด่นชัดน้อยลง",
      "ไม่มีไข้ น้ำหนักลด ต่อมน้ำเหลืองโต หรือตับม้ามโต จึงไม่มี red flags ของ malignancy ชัดเจน",
      "ภาพรวมเข้าได้กับ von Willebrand disease โดยเฉพาะ type 1",
    ],
    differentialDiagnosis: ["von Willebrand disease", "Inherited platelet function disorder", "Immune thrombocytopenia", "Hemophilia carrier with low factor level"],
    finalImpression: "สงสัย von Willebrand disease type 1",
    suggestedInvestigations: ["CBC พร้อมจำนวนเกล็ดเลือด", "PT", "aPTT", "vWF antigen", "vWF activity หรือ ristocetin cofactor activity", "Factor VIII activity", "Iron studies หากประจำเดือนมากจนสงสัย iron deficiency"],
    teachingSummary: "von Willebrand disease มักมี mucocutaneous bleeding เช่น epistaxis, gum bleeding, easy bruising และ menorrhagia มักมีประวัติครอบครัว โดย type 1 ส่วนใหญ่ถ่ายทอดแบบ autosomal dominant จึงอาจพบอาการในพ่อหรือแม่และพี่น้องได้ จำนวนเกล็ดเลือดมักปกติ และต้องยืนยันด้วย vWF antigen กับ activity",
  },
  {
    id: "apde",
    diagnosis: "Acquired platelet dysfunction with eosinophilia (APDE)",
    diagnosisCategory: "ภาวะการทำงานของเกล็ดเลือดผิดปกติร่วมกับ eosinophilia",
    identity: {
      childName: "เด็กชายปุณณวิช",
      childSurname: "ศรีเจริญ",
      childNickname: "น้องปุณณ์",
      childAge: "7 ปี",
      childSex: "ชาย",
      parentName: "นางสาวกานต์พิชชา",
      parentSurname: "ศรีเจริญ",
      informantRelationship: "มารดา",
    },
    openingStatement: "ลูกมีจ้ำเลือดขึ้นง่ายตามตัวค่ะ",
    broadAnswer: "มีจ้ำตามแขนขาเป็น ๆ หาย ๆ และมีจุดแดงเล็ก ๆ บ้างค่ะ",
    responseRules: [
      {
        id: "siblings",
        domainIds: ["family"],
        keywords: ["มีพี่น้อง", "พี่น้องไหม", "พี่หรือน้อง", "มีพี่", "มีน้อง", "พี่ชาย", "น้องชาย", "พี่สาว", "น้องสาว", "ลูกกี่คน", "ลูกคนที่"],
        answer: "มีน้องสาว 1 คน อายุ 4 ปีค่ะ สุขภาพแข็งแรงดี ไม่มีจ้ำเลือดหรือเลือดออกง่ายเหมือนน้อง",
      },
      {
        id: "vaccination",
        domainIds: [],
        keywords: ["วัคซีน", "ฉีดวัคซีน", "สมุดวัคซีน", "dtp", "opv", "โปลิโอ", "เชื้อเป็น", "live vaccine"],
        answer: "วัคซีนพื้นฐานครบตามวัยค่ะ ล่าสุดเป็นวัคซีนรวมคอตีบ-บาดทะยัก-ไอกรนเข็มกระตุ้นกับวัคซีนโปลิโอชนิดรับประทาน ตอนอายุ 4 ปี ประมาณ 3 ปีก่อนค่ะ ตอนเข้า ป.1 โรงเรียนตรวจสมุดแล้วไม่ต้องฉีดเก็บตก",
      },
      { id: "duration", domainIds: ["onset"], keywords: ["เริ่ม", "นาน", "กี่วัน", "กี่สัปดาห์", "กี่เดือน", "เมื่อไหร่"], answer: "เป็น ๆ หาย ๆ มาประมาณ 2 เดือนค่ะ" },
      { id: "pattern", domainIds: ["site", "mucocutaneous"], keywords: ["จ้ำเลือด", "จุดเลือด", "petechiae", "ecchymosis", "เลือดออกที่ไหน", "ลักษณะ", "ช้ำง่าย"], answer: "เป็นจ้ำเลือดตามแขนขา และมีจุดเลือดออกเล็ก ๆ บ้างค่ะ" },
      { id: "epistaxis", domainIds: ["site", "mucocutaneous"], keywords: ["กำเดา", "จมูก"], answer: "บางครั้งมีเลือดกำเดาเล็กน้อยค่ะ แต่หยุดเองได้" },
      { id: "severity", domainIds: ["site"], keywords: ["รุนแรง", "มาก", "หยุดยาก", "เสียเลือด"], answer: "ไม่มีเลือดออกรุนแรงค่ะ" },
      { id: "gi-gu", domainIds: ["site"], keywords: ["ถ่ายดำ", "ถ่ายเลือด", "อุจจาระ", "ปัสสาวะ", "ฉี่"], answer: "ไม่มีถ่ายดำ ถ่ายเลือด หรือปัสสาวะเป็นเลือดค่ะ" },
      { id: "deep", domainIds: ["deep"], keywords: ["ข้อบวม", "ปวดข้อ", "เข่าบวม", "เลือดออกในข้อ", "กล้ามเนื้อ", "ช้ำลึก"], answer: "ไม่มีข้อบวมหรือกล้ามเนื้อบวมค่ะ" },
      { id: "trauma", domainIds: ["trauma"], keywords: ["กระแทก", "อุบัติเหตุ", "ล้ม", "ถอนฟัน", "ผ่าตัด", "ขลิบ", "ฉีดยา"], answer: "จ้ำบางจุดขึ้นเองทั้งที่ไม่ได้กระแทกแรงค่ะ ไม่เคยมีเลือดออกมากหลังหัตถการ" },
      { id: "infection", domainIds: ["infection"], keywords: ["ไข้", "หวัด", "ไอ", "เจ็บคอ", "ท้องเสีย", "ติดเชื้อ", "ป่วยก่อน"], answer: "ไม่มีไข้หรืออาการติดเชื้อก่อนหน้านี้ค่ะ" },
      { id: "allergy", domainIds: [], keywords: ["แพ้", "ภูมิแพ้", "คัน", "ผื่น", "หอบ"], answer: "มีคันผิวหนังหรือเป็นผื่นภูมิแพ้บ้างค่ะ" },
      { id: "parasite", domainIds: [], keywords: ["พยาธิ", "เล่นดิน", "เท้าเปล่า", "สุก ๆ ดิบ ๆ", "สุกๆดิบๆ", "ปวดท้อง"], answer: "ชอบเล่นดิน เดินเท้าเปล่าบ้างค่ะ บางครั้งในบ้านก็กินอาหารสุก ๆ ดิบ ๆ" },
      { id: "medication", domainIds: ["medication"], keywords: ["ยา", "aspirin", "แอสไพริน", "nsaid", "ibuprofen", "สมุนไพร", "อาหารเสริม"], answer: "ไม่ได้กิน aspirin หรือยาแก้อักเสบค่ะ" },
      { id: "redflags", domainIds: ["redflags"], keywords: ["ซีด", "น้ำหนัก", "เบื่ออาหาร", "ปวดกระดูก", "ต่อมน้ำเหลือง", "ตับ", "ม้าม", "ท้องโต", "เหงื่อกลางคืน"], answer: "ไม่มีไข้ ไม่มีน้ำหนักลด ไม่มีปวดกระดูก ไม่เห็นต่อมน้ำเหลืองโตหรือท้องโตค่ะ" },
      { id: "family", domainIds: ["family"], keywords: ["ครอบครัว", "ญาติ", "น้า", "ลุง", "พี่น้อง", "hemophilia", "ฮีโมฟีเลีย", "von willebrand", "กรรมพันธุ์"], answer: "ไม่มีใครในครอบครัวเลือดออกง่ายค่ะ" },
      { id: "past", domainIds: [], keywords: ["เคยเป็น", "เคยเลือดออก", "เคยได้รับเลือด", "เคยนอน", "โรคประจำตัว", "เคยตรวจเลือด", "เกล็ดเลือดต่ำ"], answer: "ไม่มีโรคประจำตัว ไม่เคยเกล็ดเลือดต่ำ และไม่เคยได้รับเลือดค่ะ" },
    ],
    physicalExam: {
      positives: ["พบจ้ำเลือดหลายตำแหน่งที่แขนขา", "พบจุดเลือดออกเล็กน้อย", "มีรอยเกาจากผื่นคันเล็กน้อย"],
      negatives: ["ไม่ซีดชัดเจน", "ไม่มีตาเหลือง", "ไม่พบต่อมน้ำเหลืองโต", "ตับและม้ามไม่โต", "ไม่มีข้อบวม"],
    },
    expectedLabPattern: [
      "CBC: Hb ปกติ, WBC ปกติหรือมี eosinophil สูง และจำนวนเกล็ดเลือดปกติ",
      "Absolute eosinophil count สูง",
      "PT และ aPTT ปกติ",
      "Platelet function test ผิดปกติ",
      "Stool examination อาจพบพยาธิหรืออาจไม่พบ ขึ้นกับสาเหตุ",
    ],
    investigationScores: [
      score("cbc", "เลือก CBC พร้อม differential และจำนวนเกล็ดเลือด", 6, ["cbc"]),
      score("eosinophil", "เลือก absolute eosinophil count", 4, ["eosinophil"]),
      score("coag", "เลือก PT และ aPTT เพื่อคัดกรอง coagulation disorder", 4, ["pt", "aptt"]),
      score("platelet", "เลือก platelet function test", 4, ["plateletFunction"]),
      score("stool", "เลือกตรวจอุจจาระหาไข่พยาธิและพยาธิ", 2, ["stool"]),
    ],
    investigationNotes: {
      ...standardScreeningNotes,
      eosinophil: "เป็นข้อมูลสำคัญที่เชื่อม clinical pattern เข้ากับ APDE",
      plateletFunction: "ช่วยแสดงความผิดปกติของการทำงานเกล็ดเลือดแม้จำนวนเกล็ดเลือดปกติ",
      stool: "เหมาะเมื่อมีประวัติ exposure ที่เสี่ยงต่อพยาธิ",
      boneMarrow: "ยังไม่มีข้อบ่งชี้ในเด็กที่ไม่มี cytopenia หรือ red flags ของ malignancy",
    },
    problemScoring: {
      patternKeywords: ["mucocutaneous", "เยื่อบุ", "ผิวหนัง", "platelet", "เกล็ดเลือด", "จ้ำเลือด", "จุดเลือด"],
      positiveKeywords: ["2 เดือน", "สองเดือน", "จ้ำเลือด", "จุดเลือด", "กำเดา", "ภูมิแพ้", "คัน", "เล่นดิน", "เท้าเปล่า", "พยาธิ"],
      negativeKeywords: ["ไม่มีข้อ", "ไม่มีกล้ามเนื้อ", "ไม่มีไข้", "ไม่มีน้ำหนัก", "ตับม้ามไม่โต", "ไม่มีต่อมน้ำเหลือง"],
      differentialKeywords: ["apde", "platelet dysfunction", "itp", "von willebrand", "eosinophilia", "พยาธิ"],
      impressionKeywords: ["apde", "acquired platelet dysfunction", "platelet dysfunction with eosinophilia"],
    },
    modelProblemList: [
      "เด็กชายอายุ 7 ปี มี recurrent mucocutaneous bleeding เป็น ๆ หาย ๆ 2 เดือน ได้แก่ ecchymoses, petechiae และ epistaxis เล็กน้อย",
      "ไม่มี severe bleeding, GI bleeding, GU bleeding, joint bleeding หรือ muscle bleeding",
      "ไม่มีไข้ น้ำหนักลด ปวดกระดูก ต่อมน้ำเหลืองโต หรือตับม้ามโต จึงไม่มี red flags ของ leukemia หรือ systemic illness ชัดเจน",
      "มีประวัติภูมิแพ้ คันผิวหนัง และ exposure ที่อาจเกี่ยวกับ eosinophilia หรือพยาธิ",
      "ภาพรวมเข้าได้กับ platelet-type bleeding หากจำนวนเกล็ดเลือดปกติแต่มี eosinophilia ควรนึกถึง APDE",
    ],
    differentialDiagnosis: ["Acquired platelet dysfunction with eosinophilia", "von Willebrand disease", "Immune thrombocytopenia", "Inherited platelet function disorder"],
    finalImpression: "สงสัย acquired platelet dysfunction with eosinophilia (APDE)",
    suggestedInvestigations: ["CBC พร้อมจำนวนเกล็ดเลือดและ differential count", "Absolute eosinophil count", "Peripheral blood smear", "PT", "aPTT", "Platelet function test หากมี", "ตรวจอุจจาระหาไข่พยาธิและพยาธิ", "ประเมินโรคภูมิแพ้หรือการติดพยาธิตามบริบท"],
    teachingSummary: "APDE เป็นภาวะ platelet dysfunction ที่พบร่วมกับ eosinophilia ผู้ป่วยมักมี mucocutaneous bleeding แต่จำนวนเกล็ดเลือดและ coagulation screening อาจปกติ การถามประวัติภูมิแพ้ พยาธิ และ exposure จึงมีความสำคัญ",
  },
];

export function selectRandomBleedingCase(previousCaseId?: BleedingCase["id"]): BleedingCase {
  const available =
    bleedingCases.length > 1 && previousCaseId
      ? bleedingCases.filter((item) => item.id !== previousCaseId)
      : bleedingCases;
  return available[Math.floor(Math.random() * available.length)];
}
