import type { SimulationCase } from "./types";

// Educator-editable case bank.
// Add or revise cases here: history response rules, scoring rubrics, physical findings,
// model problem lists, investigations, and teaching summaries all live in this file.
export const cases: SimulationCase[] = [
  {
    id: "iron-deficiency-anemia",
    diagnosis: "Iron deficiency anemia",
    age: "เด็กอายุ 5 ปี",
    patientIdentity: {
      childName: "เด็กชายพีรวิชญ์",
      childSurname: "ใจดี",
      childNickname: "น้องพีท",
      childAge: "5 ปี",
      childSex: "ชาย",
      motherName: "นางสาวศิริพร",
      motherSurname: "ใจดี",
      relationship: "มารดา",
    },
    openingStatement: "สังเกตว่าลูกดูซีด",
    broadAnswer: "ก็เห็นว่าซีดลง แล้วดูเพลียขึ้นค่ะ",
    responseRules: [
      { id: "duration", domainIds: ["duration"], keywords: ["นาน", "กี่วัน", "กี่สัปดาห์", "กี่เดือน", "เริ่ม", "ตั้งแต่เมื่อไหร่", "ซีดมานาน"], answer: "ประมาณ 1 เดือนค่ะ" },
      { id: "progression", domainIds: ["progression"], keywords: ["มากขึ้น", "แย่ลง", "ซีดขึ้น", "รุนแรง", "เป็นมาก", "ค่อย ๆ", "เฉียบพลัน"], answer: "ค่อย ๆ ซีดลงค่ะ ไม่ได้เป็นทันทีทันใด" },
      { id: "fatigue", domainIds: ["fatigue"], keywords: ["เหนื่อย", "อ่อนเพลีย", "เพลีย", "ไม่มีแรง", "เล่นได้น้อย", "กิจกรรม", "ซึม"], answer: "มีค่ะ ดูเพลีย ๆ เหนื่อยง่ายกว่าเดิม เล่นได้น้อยลงนิดหน่อยค่ะ" },
      { id: "bleeding", domainIds: ["bleeding"], keywords: ["เลือดออก", "เลือดกำเดา", "เลือดออกตามไรฟัน", "จ้ำเลือด", "จุดเลือด", "ฟกช้ำ", "ถ่ายดำ", "ถ่ายเลือด", "อุจจาระมีเลือด", "ปัสสาวะเป็นเลือด"], answer: "ไม่มีเลือดออกผิดปกติค่ะ ไม่มีเลือดกำเดา ไม่มีจ้ำเลือด ถ่ายก็ไม่ได้ดำหรือมีเลือดค่ะ" },
      { id: "hemolysis", domainIds: ["hemolysis"], keywords: ["ตัวเหลือง", "ตาเหลือง", "ดีซ่าน", "ปัสสาวะสีเข้ม", "ปัสสาวะดำ", "ปัสสาวะสีชา", "ปัสสาวะแดง", "เหลืองแรกเกิด", "ซีดเป็น ๆ หาย ๆ"], answer: "ไม่มีตัวเหลืองหรือตาเหลืองค่ะ ปัสสาวะสีเหลืองใสปกติค่ะ" },
      { id: "stool", domainIds: ["bleeding"], keywords: ["อุจจาระ", "ถ่าย"], answer: "อุจจาระสีน้ำตาลปกติค่ะ ไม่ดำ ไม่มีเลือดค่ะ" },
      { id: "fever", domainIds: ["fever"], keywords: ["ไข้", "ติดเชื้อ", "ไอ", "หวัด", "เจ็บคอ", "ท้องเสีย", "ป่วยก่อนหน้า"], answer: "ไม่มีไข้ค่ะ" },
      { id: "malignancy", domainIds: ["malignancy"], keywords: ["น้ำหนักลด", "เบื่ออาหาร", "ปวดกระดูก", "ปวดขา", "ปวดกลางคืน", "ต่อมน้ำเหลือง", "ก้อน", "ท้องโต", "ตับ", "ม้าม", "เหงื่อกลางคืน"], answer: "ไม่มีน้ำหนักลดชัดเจน ไม่มีปวดกระดูก ไม่เห็นต่อมน้ำเหลืองโต แล้วท้องก็ไม่ได้โตค่ะ" },
      { id: "diet", domainIds: ["diet"], keywords: ["กินอะไร", "อาหาร", "รับประทาน", "กินข้าว", "กินได้ไหม", "เนื้อ", "หมู", "ไก่", "ปลา", "ตับ", "เครื่องใน", "ไข่", "ไข่แดง", "ไข่ขาว", "นม", "uht", "เลือกกิน", "pica", "กินดิน", "กินน้ำแข็ง"], answer: "ลูกไม่ค่อยกินเนื้อสัตว์ค่ะ ไม่กินเครื่องใน กินแต่ไข่ขาวไม่กินไข่แดง แล้วดื่มนม UHT วันละประมาณ 6 กล่องค่ะ" },
      { id: "birth", domainIds: ["hemolysis"], keywords: ["แรกเกิด", "ตัวเหลืองแรกเกิด", "ส่องไฟ", "คลอด", "น้ำหนักแรกเกิด", "ได้รับเลือดแรกเกิด", "บุตรคนที่", "ลำดับที่"], answer: "เป็นลูกคนแรกค่ะ ตอนแรกเกิดไม่มีตัวเหลือง ไม่เคยส่องไฟค่ะ" },
      { id: "antenatal", domainIds: ["family"], keywords: ["ฝากครรภ์", "ผลเลือดแม่", "แม่ซีด", "ตั้งครรภ์", "พาหะ", "ธาลัสซีเมียตอนฝากครรภ์"], answer: "แม่ฝากครรภ์ปกติ ผลเลือดตอนฝากครรภ์ก็ปกติค่ะ" },
      { id: "past", domainIds: ["past"], keywords: ["โรคประจำตัว", "เคยเจาะเลือด", "เคยได้เลือด", "เคยได้รับเลือด", "นอนโรงพยาบาล", "กินยา", "ยาเรื้อรัง"], answer: "ไม่มีโรคประจำตัวค่ะ ไม่เคยเจาะเลือดมาก่อน และไม่เคยได้รับเลือดค่ะ" },
      { id: "family", domainIds: ["family"], keywords: ["คนในครอบครัว", "พ่อแม่ซีด", "ธาลัสซีเมีย", "โลหิตจาง", "เลือดจาง", "เม็ดเลือดแดงเล็ก", "ตัวเหลืองในครอบครัว", "ตัดม้าม", "ได้รับเลือด", "ญาติ"], answer: "ไม่มีใครในครอบครัวเป็นโลหิตจางหรือธาลัสซีเมียที่ทราบค่ะ" },
    ],
    physicalExam: {
      positives: ["Pale conjunctiva — เยื่อบุตาซีด", "Koilonychia — เล็บรูปช้อน"],
      negatives: ["No icteric sclera — ไม่มีตาเหลือง", "No lymph node enlargement — ไม่พบต่อมน้ำเหลืองโต", "No hepatosplenomegaly — ตับและม้ามไม่โต"],
    },
    caseSpecificRubric: [
      { id: "meat", label: "ถามการกินเนื้อสัตว์", points: 4, keywords: ["เนื้อ", "หมู", "ไก่", "ปลา", "เนื้อสัตว์"], missedPrompt: "ควรถามการกินเนื้อสัตว์หรืออาหารที่มีธาตุเหล็ก" },
      { id: "organ", label: "ถามเครื่องในหรือตับ", points: 4, keywords: ["ตับ", "เครื่องใน"], missedPrompt: "ควรถามการกินตับหรือเครื่องใน" },
      { id: "yolk", label: "ถามไข่แดง", points: 4, keywords: ["ไข่แดง", "ไข่"], missedPrompt: "ควรถามการกินไข่แดง" },
      { id: "milk", label: "ถามปริมาณนม", points: 6, keywords: ["นม", "uht", "กี่กล่อง", "ปริมาณนม"], missedPrompt: "ควรถามปริมาณนมที่ดื่มต่อวัน" },
      { id: "pica", label: "ถาม pica หรือความอยากกินผิดปกติ", points: 2, keywords: ["pica", "กินดิน", "กินน้ำแข็ง", "กินแป้ง"], missedPrompt: "ควรถาม pica หรือความอยากกินสิ่งผิดปกติ" },
    ],
    problemRubric: [
      { id: "duration", label: "ระบุภาวะซีดพร้อมระยะเวลา", points: 3, keywords: ["ซีด", "โลหิตจาง", "1 เดือน", "หนึ่งเดือน", "เรื้อรัง"] },
      { id: "positive", label: "ใส่ pertinent positive สำคัญ", points: 4, keywords: ["เพลีย", "เหนื่อย", "ไม่กินเนื้อ", "ไม่กินเครื่องใน", "ไข่แดง", "นม", "6 กล่อง", "เล็บรูปช้อน"] },
      { id: "negative", label: "ใส่ pertinent negative", points: 3, keywords: ["ไม่มีเลือด", "ไม่ถ่ายดำ", "ไม่มีตัวเหลือง", "ไม่มีไข้", "ไม่พบตับม้าม", "ไม่มีต่อมน้ำเหลือง"] },
      { id: "exam", label: "เชื่อมโยงตรวจร่างกาย", points: 3, keywords: ["pale conjunctiva", "เยื่อบุตาซีด", "koilonychia", "เล็บรูปช้อน"] },
      { id: "diagnosis", label: "เสนอ diagnostic direction", points: 2, keywords: ["iron deficiency", "ขาดธาตุเหล็ก", "ดื่มนมมาก", "อาหารธาตุเหล็กต่ำ"] },
    ],
    modelProblemList: [
      "เด็กอายุ 5 ปี มีอาการซีดเรื้อรังประมาณ 1 เดือน",
      "มีอาการอ่อนเพลียร่วมด้วย",
      "มีประวัติรับประทานอาหารที่มีธาตุเหล็กต่ำ ได้แก่ ไม่กินเนื้อสัตว์ ไม่กินเครื่องใน และไม่กินไข่แดง",
      "ดื่มนม UHT มาก วันละประมาณ 6 กล่อง ซึ่งเป็นปัจจัยเสี่ยงต่อ iron deficiency anemia",
      "ไม่มีประวัติเลือดออกผิดปกติ อุจจาระสีน้ำตาลปกติ ทำให้ภาวะเสียเลือดเด่นชัดมีโอกาสน้อยลง",
      "ไม่มีตัวเหลือง ไม่มีตาเหลือง และปัสสาวะสีปกติ ทำให้ hemolysis เด่นชัดมีโอกาสน้อยลง",
      "ไม่มีไข้ ไม่มีต่อมน้ำเหลืองโต และตรวจไม่พบตับม้ามโต ทำให้ leukemia หรือ systemic malignancy ยังไม่มี red flags ชัดเจน",
      "ตรวจร่างกายพบ pale conjunctiva และ koilonychia ซึ่งสนับสนุนภาวะโลหิตจางจากการขาดธาตุเหล็ก",
    ],
    finalImpression: "ภาวะโลหิตจางจากการขาดธาตุเหล็ก หรือ iron deficiency anemia จาก dietary iron deficiency และ excessive milk intake",
    suggestedInvestigations: ["CBC with red cell indices", "Reticulocyte count", "Peripheral blood smear", "Serum ferritin", "Serum iron, TIBC, transferrin saturation if available", "Stool occult blood if history suggests GI blood loss", "Hemoglobin typing if microcytic anemia is found or thalassemia remains a concern"],
    teachingSummary: "ภาวะซีดจาก iron deficiency anemia มักสัมพันธ์กับประวัติได้รับธาตุเหล็กไม่เพียงพอ เช่น ไม่กินเนื้อสัตว์ ไม่กินไข่แดง ไม่กินเครื่องใน และดื่มนมมากเกินไป การซักประวัติอาหารจึงเป็นหัวใจสำคัญของเคสนี้",
  },
  {
    id: "thalassemia",
    diagnosis: "Thalassemia disease",
    age: "เด็กอายุ 4 ปี",
    patientIdentity: {
      childName: "เด็กหญิงณัฐณิชา",
      childSurname: "แสงทอง",
      childNickname: "น้องน้ำฟ้า",
      childAge: "4 ปี",
      childSex: "หญิง",
      motherName: "นางสาวกมลวรรณ",
      motherSurname: "แสงทอง",
      relationship: "มารดา",
    },
    openingStatement: "สังเกตว่าลูกดูซีด",
    broadAnswer: "ก็เห็นว่าซีดมานาน แล้วช่วงหลังดูเพลียและท้องโตขึ้นค่ะ",
    responseRules: [
      { id: "duration", domainIds: ["duration", "progression"], keywords: ["นาน", "กี่วัน", "กี่สัปดาห์", "กี่เดือน", "เริ่ม", "ตั้งแต่เมื่อไหร่", "ซีดมานาน", "มากขึ้น", "แย่ลง", "ซีดขึ้น", "ค่อย ๆ"], answer: "จริง ๆ เหมือนซีดมาหลายเดือนแล้วค่ะ แต่ช่วง 1-2 เดือนนี้ดูซีดชัดขึ้น" },
      { id: "fatigue", domainIds: ["fatigue"], keywords: ["เหนื่อย", "อ่อนเพลีย", "เพลีย", "ไม่มีแรง", "เล่นได้น้อย", "กิจกรรม", "ซึม"], answer: "มีค่ะ เล่นได้น้อยลง เหนื่อยง่ายกว่าเด็กวัยเดียวกันค่ะ" },
      { id: "jaundice", domainIds: ["hemolysis"], keywords: ["ตัวเหลือง", "ตาเหลือง", "ดีซ่าน", "เหลือง", "ซีดเป็น ๆ หาย ๆ"], answer: "มีค่ะ บางช่วงตาเหลือง ตัวเหลืองนิด ๆ เป็น ๆ หาย ๆ ค่ะ" },
      { id: "abdomen", domainIds: ["malignancy"], keywords: ["ท้องโต", "แน่นท้อง", "ตับ", "ม้าม", "hepatosplenomegaly"], answer: "รู้สึกว่าท้องโตขึ้นค่ะ โดยเฉพาะช่วงหลัง ๆ" },
      { id: "urine", domainIds: ["hemolysis"], keywords: ["ปัสสาวะ", "ปัสสาวะสีเข้ม", "ปัสสาวะดำ", "ปัสสาวะสีชา", "ปัสสาวะแดง"], answer: "บางครั้งปัสสาวะสีเหลืองเข้มค่ะ แต่ไม่แดง ไม่ดำ" },
      { id: "bleeding", domainIds: ["bleeding"], keywords: ["เลือดออก", "เลือดกำเดา", "เลือดออกตามไรฟัน", "จ้ำเลือด", "จุดเลือด", "ฟกช้ำ", "ถ่ายดำ", "ถ่ายเลือด", "อุจจาระมีเลือด"], answer: "ไม่มีเลือดออกผิดปกติค่ะ ไม่มีเลือดกำเดา ไม่มีจ้ำเลือด ถ่ายไม่ดำ ไม่มีเลือดค่ะ" },
      { id: "fever", domainIds: ["fever"], keywords: ["ไข้", "ติดเชื้อ", "ไอ", "หวัด", "เจ็บคอ", "ท้องเสีย", "ป่วยก่อนหน้า"], answer: "ไม่มีไข้ค่ะ" },
      { id: "redflags", domainIds: ["malignancy"], keywords: ["น้ำหนักลด", "เบื่ออาหาร", "ปวดกระดูก", "ปวดขา", "ปวดกลางคืน", "ต่อมน้ำเหลือง", "ก้อน", "เหงื่อกลางคืน"], answer: "ไม่มีไข้ ไม่มีน้ำหนักลดชัดเจน ไม่มีปวดกระดูกค่ะ แต่ท้องดูโตขึ้นค่ะ" },
      { id: "growth", domainIds: ["malignancy"], keywords: ["โตช้า", "เจริญเติบโต", "น้ำหนัก", "ส่วนสูง"], answer: "รู้สึกว่าโตช้ากว่าเด็กวัยเดียวกันนิดหน่อยค่ะ" },
      { id: "diet", domainIds: ["diet"], keywords: ["กินอะไร", "อาหาร", "รับประทาน", "กินข้าว", "เนื้อ", "หมู", "ไก่", "ปลา", "ตับ", "เครื่องใน", "ไข่", "นม", "เลือกกิน"], answer: "รับประทานอาหารได้ปกติค่ะ" },
      { id: "birth", domainIds: ["hemolysis"], keywords: ["แรกเกิด", "ตัวเหลืองแรกเกิด", "ส่องไฟ", "คลอด", "ได้รับเลือดแรกเกิด"], answer: "ตอนแรกเกิดเหมือนเหลืองนิดหน่อยค่ะ แต่ไม่ได้ส่องไฟ และไม่เคยได้รับเลือดค่ะ" },
      { id: "antenatal", domainIds: ["family"], keywords: ["ฝากครรภ์", "ผลเลือดแม่", "แม่ซีด", "ตั้งครรภ์", "พาหะ", "ธาลัสซีเมียตอนฝากครรภ์"], answer: "แม่ฝากครรภ์ปกติค่ะ จำได้ว่ามีตรวจเลือด แต่ไม่แน่ใจเรื่องพาหะธาลัสซีเมียค่ะ" },
      { id: "parentblood", domainIds: ["family"], keywords: ["ผลเลือดพ่อ", "ผลเลือดแม่", "เม็ดเลือดแดงเล็ก", "พ่อแม่ซีด"], answer: "แม่เคยถูกบอกว่าเม็ดเลือดแดงเล็กหรือเลือดจางนิดหน่อยค่ะ แต่ไม่ได้รักษาอะไร" },
      { id: "past", domainIds: ["past"], keywords: ["โรคประจำตัว", "เคยเจาะเลือด", "เคยได้เลือด", "เคยได้รับเลือด", "นอนโรงพยาบาล", "กินยา", "ยาเรื้อรัง"], answer: "เคยมีหมอบอกว่าซีดตอนอายุประมาณ 2-3 ปีค่ะ แต่ไม่ได้ติดตามต่อเนื่อง ไม่เคยได้รับเลือดค่ะ" },
      { id: "family", domainIds: ["family"], keywords: ["คนในครอบครัว", "ธาลัสซีเมีย", "โลหิตจาง", "เลือดจาง", "เม็ดเลือดแดงเล็ก", "ตัวเหลืองในครอบครัว", "ตัดม้าม", "ได้รับเลือด", "ญาติ"], answer: "แม่เคยถูกบอกว่าเลือดจางนิดหน่อยหรือเม็ดเลือดแดงเล็กค่ะ แต่ไม่แน่ใจว่าเป็นธาลัสซีเมียไหม" },
    ],
    physicalExam: {
      positives: ["Pale conjunctiva — เยื่อบุตาซีด", "Icteric sclera — ตาเหลือง", "Hepatosplenomegaly — ตับและม้ามโต"],
      negatives: ["No lymph node enlargement — ไม่พบต่อมน้ำเหลืองโต", "No petechiae — ไม่พบจุดเลือดออก", "No active bleeding — ไม่มีเลือดออกผิดปกติขณะตรวจ"],
    },
    caseSpecificRubric: [
      { id: "jaundice", label: "ถามตัวเหลืองหรือตาเหลือง", points: 5, keywords: ["ตัวเหลือง", "ตาเหลือง", "ดีซ่าน", "เหลือง"], missedPrompt: "ควรถามอาการตัวเหลืองหรือตาเหลือง" },
      { id: "abdomen", label: "ถามท้องโตหรือตับม้ามโต", points: 5, keywords: ["ท้องโต", "ตับ", "ม้าม", "แน่นท้อง"], missedPrompt: "ควรถามท้องโตหรือตับม้ามโต" },
      { id: "family", label: "ถามประวัติครอบครัวโรคเลือด", points: 5, keywords: ["ครอบครัว", "ธาลัสซีเมีย", "โลหิตจาง", "เลือดจาง", "ตัดม้าม", "ได้รับเลือด", "ญาติ"], missedPrompt: "ควรถามประวัติครอบครัวเกี่ยวกับธาลัสซีเมีย โลหิตจาง ตัวเหลือง หรือการตัดม้าม" },
      { id: "neonatal", label: "ถามตัวเหลืองแรกเกิดหรือซีดตั้งแต่เล็ก", points: 3, keywords: ["แรกเกิด", "ส่องไฟ", "ตัวเหลืองแรกเกิด", "อายุ 2", "อายุ 3"], missedPrompt: "ควรถามประวัติตัวเหลืองแรกเกิดหรือประวัติซีดตั้งแต่เล็ก" },
      { id: "growth", label: "ถามการเจริญเติบโตหรือความเรื้อรัง", points: 2, keywords: ["โตช้า", "เจริญเติบโต", "หลายเดือน", "เรื้อรัง"], missedPrompt: "ควรถามการเจริญเติบโตและความเรื้อรังของอาการซีด" },
    ],
    problemRubric: [
      { id: "duration", label: "ระบุซีดเรื้อรัง", points: 3, keywords: ["ซีด", "หลายเดือน", "เรื้อรัง", "1-2 เดือน", "หนึ่งถึงสองเดือน"] },
      { id: "positive", label: "ใส่ pertinent positive สำคัญ", points: 4, keywords: ["ตาเหลือง", "ตัวเหลือง", "ท้องโต", "ตับ", "ม้าม", "โตช้า", "เม็ดเลือดแดงเล็ก"] },
      { id: "negative", label: "ใส่ pertinent negative", points: 3, keywords: ["ไม่มีเลือด", "ไม่มีไข้", "ไม่มีจ้ำ", "ไม่มีต่อมน้ำเหลือง", "ไม่ถ่ายดำ"] },
      { id: "exam", label: "เชื่อมโยงตรวจร่างกาย", points: 3, keywords: ["pale conjunctiva", "เยื่อบุตาซีด", "icteric", "ตาเหลือง", "hepatosplenomegaly", "ตับม้ามโต"] },
      { id: "diagnosis", label: "เสนอ diagnostic direction", points: 2, keywords: ["thalassemia", "ธาลัสซีเมีย", "chronic hemolytic", "hemolysis", "เม็ดเลือดแดงแตก"] },
    ],
    modelProblemList: [
      "เด็กอายุ 4 ปี มีอาการซีดเรื้อรัง และช่วงหลังซีดชัดขึ้น",
      "มีอ่อนเพลีย เล่นได้น้อยลง",
      "มีประวัติตัวเหลืองและตาเหลืองเป็น ๆ หาย ๆ สนับสนุน chronic hemolysis",
      "แม่สังเกตว่าท้องโตขึ้น ซึ่งสอดคล้องกับ hepatosplenomegaly",
      "มีประวัติครอบครัวที่อาจเข้าได้กับพาหะธาลัสซีเมียหรือเม็ดเลือดแดงเล็ก",
      "ไม่มีเลือดออกผิดปกติ ไม่มีถ่ายดำหรือถ่ายเป็นเลือด ทำให้ภาวะเสียเลือดเด่นชัดมีโอกาสน้อยลง",
      "ตรวจร่างกายพบ pale conjunctiva, icteric sclera และ hepatosplenomegaly",
      "ภาพรวมเข้าได้กับ chronic hemolytic anemia โดยควรนึกถึง thalassemia disease เป็นลำดับต้น ๆ",
    ],
    finalImpression: "สงสัย thalassemia disease หรือ chronic hemolytic anemia",
    suggestedInvestigations: ["CBC with red cell indices", "Reticulocyte count", "Peripheral blood smear", "Hemoglobin typing", "Serum bilirubin", "LDH", "Ferritin", "Direct antiglobulin test if immune hemolysis remains possible", "Consider alpha/beta-globin genetic testing depending on hemoglobin typing result"],
    teachingSummary: "Thalassemia disease มักมีลักษณะซีดเรื้อรังร่วมกับตัวเหลือง ตาเหลือง และตับม้ามโต ประวัติครอบครัวที่มีโลหิตจาง เม็ดเลือดแดงเล็ก ตัวเหลือง หรือเคยได้รับเลือด มีความสำคัญมาก",
  },
  {
    id: "acute-leukemia",
    diagnosis: "Acute leukemia presenting with anemia",
    age: "เด็กอายุ 6 ปี",
    patientIdentity: {
      childName: "เด็กชายธนกฤต",
      childSurname: "วงศ์สุวรรณ",
      childNickname: "น้องต้นกล้า",
      childAge: "6 ปี",
      childSex: "ชาย",
      motherName: "นางสาวอรพรรณ",
      motherSurname: "วงศ์สุวรรณ",
      relationship: "มารดา",
    },
    openingStatement: "สังเกตว่าลูกดูซีด",
    broadAnswer: "ซีดลง ดูเพลีย แล้วช่วงนี้เหมือนมีไข้เป็น ๆ หาย ๆ ค่ะ",
    responseRules: [
      { id: "duration", domainIds: ["duration"], keywords: ["นาน", "กี่วัน", "กี่สัปดาห์", "กี่เดือน", "เริ่ม", "ตั้งแต่เมื่อไหร่", "ซีดมานาน"], answer: "ประมาณ 3 สัปดาห์ค่ะ" },
      { id: "progression", domainIds: ["progression"], keywords: ["มากขึ้น", "แย่ลง", "ซีดขึ้น", "รุนแรง", "เป็นมาก", "ค่อย ๆ", "เฉียบพลัน"], answer: "ช่วง 3 สัปดาห์นี้ดูซีดและเพลียมากขึ้นค่ะ" },
      { id: "fatigue", domainIds: ["fatigue"], keywords: ["เหนื่อย", "อ่อนเพลีย", "เพลีย", "ไม่มีแรง", "เล่นได้น้อย", "กิจกรรม", "ซึม"], answer: "เพลียมากขึ้นค่ะ เล่นน้อยลง ดูไม่มีแรงค่ะ" },
      { id: "fever", domainIds: ["fever"], keywords: ["ไข้", "ติดเชื้อ", "ไอ", "หวัด", "เจ็บคอ", "ท้องเสีย", "ป่วยก่อนหน้า"], answer: "มีค่ะ มีไข้เป็น ๆ หาย ๆ มาประมาณ 2 สัปดาห์ และช่วงนี้ยังมีไข้เป็นบางวันค่ะ" },
      { id: "weight", domainIds: ["malignancy"], keywords: ["น้ำหนักลด", "เบื่ออาหาร", "กินได้น้อย"], answer: "ช่วงนี้เบื่ออาหารค่ะ น้ำหนักเหมือนลดลงนิดหน่อย" },
      { id: "bleeding", domainIds: ["bleeding"], keywords: ["เลือดออก", "เลือดกำเดา", "เลือดออกตามไรฟัน", "จ้ำเลือด", "จุดเลือด", "ฟกช้ำ", "petechiae"], answer: "มีจ้ำเลือดตามแขนขาค่ะ บางจุดไม่ได้ชนอะไรชัดเจน แล้วเคยมีเลือดกำเดาออก 1-2 ครั้งค่ะ" },
      { id: "stool", domainIds: ["bleeding"], keywords: ["ถ่ายดำ", "ถ่ายเลือด", "อุจจาระมีเลือด"], answer: "ไม่มีถ่ายดำหรือถ่ายเป็นเลือดค่ะ" },
      { id: "hemolysis", domainIds: ["hemolysis"], keywords: ["ตัวเหลือง", "ตาเหลือง", "ดีซ่าน", "ปัสสาวะสีเข้ม", "ปัสสาวะดำ", "ปัสสาวะสีชา", "ปัสสาวะแดง", "เหลืองแรกเกิด"], answer: "ไม่มีตัวเหลืองชัดเจนค่ะ ปัสสาวะสีปกติ" },
      { id: "bone", domainIds: ["malignancy"], keywords: ["ปวดกระดูก", "ปวดขา", "ปวดกลางคืน", "ปวดข้อ"], answer: "มีบ่นปวดขาหรือปวดกระดูกบ้างค่ะ โดยเฉพาะตอนกลางคืน" },
      { id: "nodes", domainIds: ["malignancy"], keywords: ["ต่อมน้ำเหลือง", "ก้อน", "คอโต"], answer: "แม่คลำเจอก้อนเล็ก ๆ แถวคอค่ะ" },
      { id: "abdomen", domainIds: ["malignancy"], keywords: ["ท้องโต", "แน่นท้อง", "ตับ", "ม้าม"], answer: "เหมือนมีแน่นท้องหรือท้องอืดนิดหน่อยค่ะ" },
      { id: "diet", domainIds: ["diet"], keywords: ["กินอะไร", "อาหาร", "รับประทาน", "กินข้าว", "เนื้อ", "หมู", "ไก่", "ปลา", "ตับ", "เครื่องใน", "ไข่", "นม", "เลือกกิน"], answer: "รับประทานอาหารได้ปกติค่ะ" },
      { id: "birth", domainIds: ["hemolysis"], keywords: ["แรกเกิด", "ตัวเหลืองแรกเกิด", "ส่องไฟ", "คลอด", "ได้รับเลือดแรกเกิด"], answer: "แรกเกิดไม่มีตัวเหลืองผิดปกติ ไม่เคยได้รับเลือดค่ะ" },
      { id: "past", domainIds: ["past"], keywords: ["โรคประจำตัว", "เคยเจาะเลือด", "เคยได้เลือด", "เคยได้รับเลือด", "นอนโรงพยาบาล", "กินยา", "ยาเรื้อรัง", "ยาเคมี", "รังสี"], answer: "ไม่มีโรคประจำตัวค่ะ ไม่เคยเจาะเลือดมาก่อน และไม่เคยได้รับเลือดค่ะ" },
      { id: "family", domainIds: ["family"], keywords: ["คนในครอบครัว", "พ่อแม่ซีด", "ธาลัสซีเมีย", "โลหิตจาง", "เลือดจาง", "มะเร็งเม็ดเลือดขาว", "ญาติ"], answer: "ไม่มีใครในครอบครัวเป็นโลหิตจาง ธาลัสซีเมีย หรือมะเร็งเม็ดเลือดขาวที่ทราบค่ะ" },
    ],
    physicalExam: {
      positives: ["Pale conjunctiva — เยื่อบุตาซีด", "Multiple ecchymoses — พบจ้ำเลือดหลายตำแหน่ง", "Cervical lymph node enlargement — ต่อมน้ำเหลืองบริเวณคอโต", "Mild hepatosplenomegaly — ตับและม้ามโตเล็กน้อย"],
      negatives: ["No icteric sclera — ไม่มีตาเหลือง", "No signs of active massive bleeding — ไม่มีเลือดออกมากขณะตรวจ"],
    },
    caseSpecificRubric: [
      { id: "fever", label: "ถามไข้", points: 4, keywords: ["ไข้", "ตัวร้อน"], missedPrompt: "ควรถามไข้หรืออาการติดเชื้อร่วม" },
      { id: "bleeding", label: "ถามเลือดออกง่ายหรือจ้ำเลือด", points: 4, keywords: ["เลือด", "จ้ำ", "ฟกช้ำ", "เลือดกำเดา", "petechiae"], missedPrompt: "ควรถามเลือดออกง่าย จ้ำเลือด จุดเลือด หรือเลือดกำเดา" },
      { id: "bone", label: "ถามปวดกระดูก", points: 4, keywords: ["ปวดกระดูก", "ปวดขา", "ปวดกลางคืน"], missedPrompt: "ควรถามปวดกระดูกหรือปวดขากลางคืน" },
      { id: "weight", label: "ถามน้ำหนักลดหรือเบื่ออาหาร", points: 3, keywords: ["น้ำหนักลด", "เบื่ออาหาร", "กินได้น้อย"], missedPrompt: "ควรถามน้ำหนักลดหรือเบื่ออาหาร" },
      { id: "nodes", label: "ถามต่อมน้ำเหลือง", points: 3, keywords: ["ต่อมน้ำเหลือง", "ก้อน"], missedPrompt: "ควรถามต่อมน้ำเหลืองหรือก้อนผิดปกติ" },
      { id: "abdomen", label: "ถามท้องโตหรือตับม้ามโต", points: 2, keywords: ["ท้องโต", "แน่นท้อง", "ตับ", "ม้าม"], missedPrompt: "ควรถามท้องโต แน่นท้อง หรือตับม้ามโต" },
    ],
    problemRubric: [
      { id: "duration", label: "ระบุซีดพร้อมระยะเวลา", points: 3, keywords: ["ซีด", "3 สัปดาห์", "สามสัปดาห์"] },
      { id: "positive", label: "ใส่ pertinent positive สำคัญ", points: 4, keywords: ["ไข้", "จ้ำเลือด", "เลือดกำเดา", "ปวดกระดูก", "ปวดขา", "เบื่ออาหาร", "น้ำหนักลด", "ต่อมน้ำเหลือง"] },
      { id: "negative", label: "ใส่ pertinent negative", points: 3, keywords: ["ไม่มีตัวเหลือง", "ปัสสาวะสีปกติ", "ไม่มีถ่ายดำ", "ไม่มีถ่ายเป็นเลือด"] },
      { id: "exam", label: "เชื่อมโยงตรวจร่างกาย", points: 3, keywords: ["pale conjunctiva", "เยื่อบุตาซีด", "ecchymoses", "จ้ำเลือด", "lymph node", "ต่อมน้ำเหลือง", "hepatosplenomegaly", "ตับม้ามโต"] },
      { id: "diagnosis", label: "เสนอ diagnostic direction", points: 2, keywords: ["acute leukemia", "leukemia", "มะเร็งเม็ดเลือดขาว", "ไขกระดูก"] },
    ],
    modelProblemList: [
      "เด็กอายุ 6 ปี มีอาการซีดประมาณ 3 สัปดาห์",
      "มีอ่อนเพลียมากขึ้นและเล่นได้น้อยลง",
      "มีไข้เป็น ๆ หาย ๆ ประมาณ 2 สัปดาห์ ร่วมกับเบื่ออาหารและน้ำหนักลดเล็กน้อย",
      "มีจ้ำเลือดและเลือดกำเดา สะท้อน bleeding tendency หรือ thrombocytopenia",
      "มีปวดขาหรือปวดกระดูก โดยเฉพาะกลางคืน",
      "มีต่อมน้ำเหลืองบริเวณคอโต และตรวจพบ mild hepatosplenomegaly",
      "ไม่มีตัวเหลืองและปัสสาวะสีปกติ ทำให้ hemolysis เด่นชัดมีโอกาสน้อยลง",
      "ภาพรวมของซีดร่วมกับไข้ เลือดออกง่าย ปวดกระดูก ต่อมน้ำเหลืองโต และตับม้ามโต ทำให้ต้องสงสัย acute leukemia",
    ],
    finalImpression: "สงสัย acute leukemia presenting with anemia, bleeding tendency, fever, bone pain, lymphadenopathy, and hepatosplenomegaly",
    suggestedInvestigations: ["CBC with differential count", "Peripheral blood smear", "Reticulocyte count", "LDH", "Uric acid", "Liver and renal function tests", "Coagulation profile", "Chest X-ray if mediastinal mass is suspected", "Bone marrow aspiration and biopsy", "Flow cytometry", "Cytogenetic and molecular studies"],
    teachingSummary: "เด็กที่ซีดร่วมกับไข้ จ้ำเลือด เลือดออกง่าย ปวดกระดูก ต่อมน้ำเหลืองโต หรือตับม้ามโต ต้องนึกถึง acute leukemia และควรตรวจ CBC และ peripheral blood smear อย่างเร่งด่วน",
  },
  {
    id: "g6pd-hemolysis",
    diagnosis: "Acute hemolytic anemia, suspected G6PD deficiency",
    age: "เด็กอายุ 7 ปี",
    patientIdentity: {
      childName: "เด็กชายกฤตภาส",
      childSurname: "สุขเจริญ",
      childNickname: "น้องกันต์",
      childAge: "7 ปี",
      childSex: "ชาย",
      motherName: "นางสาวปวีณา",
      motherSurname: "สุขเจริญ",
      relationship: "มารดา",
    },
    openingStatement: "สังเกตว่าลูกดูซีด",
    broadAnswer: "ซีดลงเร็ว แล้วดูเพลียขึ้นค่ะ",
    responseRules: [
      { id: "duration", domainIds: ["duration", "progression"], keywords: ["นาน", "กี่วัน", "กี่สัปดาห์", "กี่เดือน", "เริ่ม", "ตั้งแต่เมื่อไหร่", "ซีดมานาน", "มากขึ้น", "แย่ลง", "เฉียบพลัน"], answer: "ซีดลงเร็วค่ะ ประมาณ 3-5 วันนี้เอง" },
      { id: "fatigue", domainIds: ["fatigue"], keywords: ["เหนื่อย", "อ่อนเพลีย", "เพลีย", "ไม่มีแรง", "เล่นได้น้อย", "กิจกรรม", "ซึม"], answer: "มีค่ะ ดูเพลีย ไม่มีแรงค่ะ" },
      { id: "jaundice", domainIds: ["hemolysis"], keywords: ["ตัวเหลือง", "ตาเหลือง", "ดีซ่าน", "เหลือง"], answer: "มีตาเหลือง ตัวเหลืองค่ะ เพิ่งสังเกตชัดช่วงไม่กี่วันนี้" },
      { id: "urine", domainIds: ["hemolysis"], keywords: ["ปัสสาวะสีเข้ม", "ปัสสาวะดำ", "ปัสสาวะสีชา", "ปัสสาวะแดง", "ปัสสาวะ", "ฉี่"], answer: "ช่วงนี้ปัสสาวะสีเข้มคล้ายสีชาค่ะ" },
      { id: "bleeding", domainIds: ["bleeding"], keywords: ["เลือดออก", "เลือดกำเดา", "เลือดออกตามไรฟัน", "จ้ำเลือด", "จุดเลือด", "ฟกช้ำ", "ถ่ายดำ", "ถ่ายเลือด", "อุจจาระมีเลือด"], answer: "ไม่มีเลือดออกผิดปกติค่ะ ไม่มีถ่ายดำ ไม่มีถ่ายเป็นเลือดค่ะ" },
      { id: "fever", domainIds: ["fever"], keywords: ["ไข้", "ติดเชื้อ", "ไอ", "หวัด", "เจ็บคอ", "ท้องเสีย", "ป่วยก่อนหน้า"], answer: "ก่อนหน้านี้มีไข้หรือไอเล็กน้อยประมาณสัปดาห์ก่อนค่ะ" },
      { id: "med", domainIds: ["past"], keywords: ["ยา", "ยาลดไข้", "ยาแก้อักเสบ", "ยาจากคลินิก", "กินยา"], answer: "ก่อนหน้านี้มีไข้เล็กน้อย แล้วได้ยาจากคลินิกมากินค่ะ แต่แม่ไม่ทราบชื่อยา" },
      { id: "fava", domainIds: ["diet"], keywords: ["ถั่วปากอ้า", "fava"], answer: "ก่อนหน้านี้เคยกินถั่วปากอ้าค่ะ" },
      { id: "mothball", domainIds: ["past"], keywords: ["ลูกเหม็น", "สารกระตุ้น", "สิ่งแวดล้อม", "แนฟทาลีน"], answer: "ที่บ้านมีลูกเหม็นในตู้เสื้อผ้าค่ะ" },
      { id: "bone", domainIds: ["malignancy"], keywords: ["ปวดกระดูก", "ปวดขา", "ปวดกลางคืน"], answer: "ไม่มีปวดกระดูกค่ะ" },
      { id: "nodes", domainIds: ["malignancy"], keywords: ["ต่อมน้ำเหลือง", "ก้อน", "ท้องโต", "ตับ", "ม้าม"], answer: "ไม่เห็นต่อมน้ำเหลืองโต และท้องไม่ได้โตชัดเจนค่ะ" },
      { id: "diet", domainIds: ["diet"], keywords: ["กินอะไร", "อาหาร", "รับประทาน", "กินข้าว", "เนื้อ", "หมู", "ไก่", "ปลา", "ตับ", "เครื่องใน", "ไข่", "นม", "เลือกกิน"], answer: "รับประทานอาหารได้ปกติค่ะ" },
      { id: "neonatal", domainIds: ["hemolysis"], keywords: ["แรกเกิด", "ตัวเหลืองแรกเกิด", "ส่องไฟ", "คลอด", "ได้รับเลือดแรกเกิด"], answer: "ตอนแรกเกิดเคยตัวเหลืองค่ะ ต้องส่องไฟประมาณ 3 วัน แล้วก็ดีขึ้นค่ะ" },
      { id: "g6pd", domainIds: ["past"], keywords: ["g6pd", "จีซิกพีดี", "พร่องเอนไซม์"], answer: "แม่ไม่แน่ใจว่าเคยตรวจ G6PD หรือเปล่าค่ะ" },
      { id: "past", domainIds: ["past"], keywords: ["โรคประจำตัว", "เคยเจาะเลือด", "เคยได้เลือด", "เคยได้รับเลือด", "นอนโรงพยาบาล", "ยาเรื้อรัง"], answer: "ไม่มีโรคประจำตัวที่ทราบ ไม่เคยได้รับเลือด และไม่เคยซีดรุนแรงแบบนี้มาก่อนค่ะ" },
      { id: "family", domainIds: ["family"], keywords: ["คนในครอบครัว", "ธาลัสซีเมีย", "โลหิตจาง", "เลือดจาง", "ตัวเหลืองในครอบครัว", "ญาติ", "ฝ่ายแม่"], answer: "เหมือนมีญาติผู้ชายฝ่ายแม่เคยตัวเหลืองหลังไม่สบายหรือหลังกินยาบางอย่างค่ะ แต่ไม่แน่ใจรายละเอียด" },
    ],
    physicalExam: {
      positives: ["Pale conjunctiva — เยื่อบุตาซีด", "Icteric sclera — ตาเหลือง", "Mild tachycardia — ชีพจรเร็วเล็กน้อย"],
      negatives: ["No lymph node enlargement — ไม่พบต่อมน้ำเหลืองโต", "No hepatosplenomegaly — ตับและม้ามไม่โต", "No petechiae — ไม่พบจุดเลือดออก", "No ecchymoses — ไม่พบจ้ำเลือด"],
    },
    caseSpecificRubric: [
      { id: "jaundice", label: "ถามตัวเหลือง", points: 4, keywords: ["ตัวเหลือง", "ตาเหลือง", "ดีซ่าน", "เหลือง"], missedPrompt: "ควรถามอาการตัวเหลืองหรือตาเหลือง" },
      { id: "darkurine", label: "ถามปัสสาวะสีเข้ม", points: 4, keywords: ["ปัสสาวะสีเข้ม", "ปัสสาวะดำ", "ปัสสาวะสีชา", "ปัสสาวะแดง", "ฉี่ดำ"], missedPrompt: "ควรถามปัสสาวะสีเข้มหรือสีชา" },
      { id: "infection", label: "ถามการติดเชื้อก่อนหน้า", points: 3, keywords: ["ไข้", "ติดเชื้อ", "ไอ", "หวัด", "ป่วยก่อนหน้า"], missedPrompt: "ควรถามการติดเชื้อหรือเจ็บป่วยก่อนมีอาการ" },
      { id: "meds", label: "ถามยาใหม่", points: 3, keywords: ["ยา", "ยาลดไข้", "ยาแก้อักเสบ", "ยาจากคลินิก"], missedPrompt: "ควรถามประวัติยาใหม่หรือยาจากคลินิก" },
      { id: "trigger", label: "ถามถั่วปากอ้าหรือลูกเหม็น", points: 3, keywords: ["ถั่วปากอ้า", "ลูกเหม็น", "สารกระตุ้น", "สิ่งแวดล้อม"], missedPrompt: "ควรถามถั่วปากอ้า ลูกเหม็น หรือ oxidative exposure" },
      { id: "neonatal", label: "ถามตัวเหลืองแรกเกิดหรือเคยเป็นซ้ำ", points: 3, keywords: ["แรกเกิด", "ส่องไฟ", "ตัวเหลืองแรกเกิด", "เคยซีด", "เป็นซ้ำ"], missedPrompt: "ควรถามประวัติตัวเหลืองแรกเกิดและการส่องไฟ" },
    ],
    problemRubric: [
      { id: "duration", label: "ระบุซีดเฉียบพลันพร้อมระยะเวลา", points: 3, keywords: ["ซีด", "3-5 วัน", "3 วัน", "5 วัน", "เฉียบพลัน", "เร็ว"] },
      { id: "positive", label: "ใส่ pertinent positive สำคัญ", points: 4, keywords: ["ตาเหลือง", "ตัวเหลือง", "ปัสสาวะสีเข้ม", "สีชา", "ไข้", "ยา", "ถั่วปากอ้า", "ลูกเหม็น", "ส่องไฟ"] },
      { id: "negative", label: "ใส่ pertinent negative", points: 3, keywords: ["ไม่มีเลือด", "ไม่มีถ่ายดำ", "ไม่มีต่อมน้ำเหลือง", "ไม่มีตับม้าม", "ไม่มีจ้ำเลือด"] },
      { id: "exam", label: "เชื่อมโยงตรวจร่างกาย", points: 3, keywords: ["pale conjunctiva", "เยื่อบุตาซีด", "icteric", "ตาเหลือง", "tachycardia", "ชีพจรเร็ว"] },
      { id: "diagnosis", label: "เสนอ diagnostic direction", points: 2, keywords: ["g6pd", "จีซิกพีดี", "hemolytic", "hemolysis", "เม็ดเลือดแดงแตก"] },
    ],
    modelProblemList: [
      "เด็กอายุ 7 ปี มีอาการซีดเฉียบพลันในช่วง 3-5 วัน",
      "มีอ่อนเพลียร่วมกับตาเหลืองและตัวเหลือง",
      "มีปัสสาวะสีเข้มคล้ายสีชา สนับสนุน intravascular hemolysis หรือ hemoglobinuria",
      "มีประวัติเจ็บป่วยหรือได้รับยาก่อนมีอาการ ซึ่งอาจเป็น oxidative trigger",
      "มีประวัติตัวเหลืองแรกเกิดและได้รับ phototherapy ประมาณ 3 วัน สนับสนุนความเป็นไปได้ของ G6PD deficiency",
      "ไม่มีเลือดออกผิดปกติ ไม่มีถ่ายดำหรือถ่ายเป็นเลือด ทำให้ acute blood loss มีโอกาสน้อยลง",
      "ไม่มีต่อมน้ำเหลืองโต ไม่มีตับม้ามโต ไม่มีจุดเลือดออกหรือจ้ำเลือด ทำให้ leukemia หรือ marrow infiltration ยังไม่มี red flags ชัดเจนจากการตรวจร่างกาย",
      "ตรวจร่างกายพบ pale conjunctiva, icteric sclera และ mild tachycardia",
    ],
    finalImpression: "สงสัย acute hemolytic anemia จาก G6PD deficiency",
    suggestedInvestigations: ["CBC with red cell indices", "Reticulocyte count", "Peripheral blood smear", "Total and indirect bilirubin", "LDH", "Haptoglobin if available", "Urinalysis for hemoglobinuria", "G6PD enzyme assay, preferably repeated after the acute hemolytic episode if the initial result is falsely normal", "Direct antiglobulin test if autoimmune hemolytic anemia remains in the differential diagnosis"],
    teachingSummary: "Hemolytic anemia มักมีซีดร่วมกับตัวเหลืองและปัสสาวะสีเข้ม การซักประวัติยา การติดเชื้อ อาหารหรือสารกระตุ้น เช่น ถั่วปากอ้า ลูกเหม็น และประวัติตัวเหลืองแรกเกิด มีความสำคัญในการแยกสาเหตุ โดย G6PD deficiency มักมีประวัติ neonatal jaundice และอาจกำเริบหลัง oxidative stress",
  },
];

export function selectRandomCase(): SimulationCase {
  return cases[Math.floor(Math.random() * cases.length)];
}
